/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_fabianachammer_nsend_NSender */

#ifndef _Included_at_fabianachammer_nsend_NSender
#define _Included_at_fabianachammer_nsend_NSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_fabianachammer_nsend_NSender
 * Method:    send
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_at_fabianachammer_nsend_NSender_send
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
