/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_fabianachammer_pdusend_PduSender */

#ifndef _Included_at_fabianachammer_pdusend_PduSender
#define _Included_at_fabianachammer_pdusend_PduSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_fabianachammer_pdusend_PduSender
 * Method:    send
 * Signature: (I[B[BS[B)V
 */
JNIEXPORT void JNICALL Java_at_fabianachammer_pdusend_PduSender_send
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
