/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_fabianachammer_pdusend_Sender */

#ifndef _Included_at_fabianachammer_pdusend_Sender
#define _Included_at_fabianachammer_pdusend_Sender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_fabianachammer_pdusend_Sender
 * Method:    send
 * Signature: (I[B[BS[B)V
 */
JNIEXPORT void JNICALL Java_at_fabianachammer_pdusend_Sender_send(JNIEnv *,
		jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
